stages:
  - lint

lint_backend:
  stage: lint
  image: python:3
  before_script:
    - pip install -r requirements.txt
  script:
    - black . --check --verbose --diff --color
    - flake8 --max-line-length=88 .
  tags:
    - dind
