services:
  # db:
  #   image: mysql:8.0
  #   environment:
  #     MYSQL_DATABASE: mydb
  #     MYSQL_USER: user
  #     MYSQL_PASSWORD: password
  #     MYSQL_ROOT_PASSWORD: password
  #   restart: always
  #   ports:
  #     - "3306:3306"
  #   volumes:
  #     - mysql_data:/var/lib/mysql
  gitlab-runner:
    build:
      context: .
      dockerfile: runner.dockerfile
    restart: always
    volumes:
      - config:/etc/gitlab-runner
      - ./:/app
      - builds:/app/builds
    working_dir: /app
volumes:
  # mysql_data:
  config: {}
  builds: {}
